spring:
  profiles:
    active: local # default profile

spring:
  config:
    activate:
      on-profile: common

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/dreamroad
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true

dreamroad:
  recommendation:
    base:
      url: http://localhost:8080/dir/